logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
jwt:
  secret: javainuse
couchbase:
  server:
    127.0.0.1
  username:
    admin
  password:
    password
  bucket:
    car-rental-bucket